name: Install Dependencies
description: 'Prepares the repo by installing dependencies'
inputs:
  node-version:
    description: 'The node version to setup'
    required: true
  registry-url:
    description: 'Define registry-url'
    required: false
    default: 'https://registry.npmjs.org'

# outputs: - no outputs

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.34.5
        run_install: false

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
