language: node_js
sudo: false
node_js:
  - '0.12'

cache:
  directories:
    - node_modules

env:
  global:
  - alias jasmine=./node_modules/.bin/jasmine
  - alias tsc=./node_modules/.bin/tsc
  - alias babel=./node_modules/.bin/babel

install:
  - npm install

script:
  - npm run build_cover

after_script:
  - ./node_modules/.bin/remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped.json && ./node_modules/.bin/remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped.lcov -t lcovonly && ./node_modules/.bin/remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped -t html
  - cat ./coverage/coverage-remapped.lcov  | ./node_modules/coveralls/bin/coveralls.js
