packages:
  - 'packages/*'
  - 'apps/rxjs.dev'

allowBuilds:
  '@angular/cli@13.3.11': true
  '@parcel/watcher@2.0.4': true
  core-js: false
  core-js-pure: false
  es5-ext: false
  'esbuild@0.14.11 || 0.19.11 || 0.25.12': true
  'husky@4.3.8': true
  'nice-napi@1.0.2': true
  'nx@15.9.3 || 17.3.2 || 23.1.1': true
  'protobufjs@6.11.2 || 6.11.4 || 7.2.5': true
  're2@1.20.9': true

linkWorkspacePackages: true
patchedDependencies:
  husky@4.3.8: patches/husky@4.3.8.patch

strictDepBuilds: true
