/**
 * Everything in this file is generated by the 'tools/generate-operator-patches.ts' script.
 * Any manual edits to this file will be lost next time the script is run.
 **/
import {Observable} from '../../Observable';
import {ErrorObservable} from '../../observable/throw';

Observable.throw = ErrorObservable.create;

export var _void: void;