/**
 * Everything in this file is generated by the 'tools/generate-operator-patches.ts' script.
 * Any manual edits to this file will be lost next time the script is run.
 **/
import {Observable} from '../../Observable';
import {dematerialize} from '../../operator/dematerialize';

Observable.prototype.dematerialize = dematerialize;

export var _void: void;