/**
 * Everything in this file is generated by the 'tools/generate-operator-patches.ts' script.
 * Any manual edits to this file will be lost next time the script is run.
 **/
import {Observable} from '../../Observable';
import {ignoreElements} from '../../operator/ignoreElements';

Observable.prototype.ignoreElements = ignoreElements;

export var _void: void;