/**
 * Everything in this file is generated by the 'tools/generate-operator-patches.ts' script.
 * Any manual edits to this file will be lost next time the script is run.
 **/
import {Observable} from '../../Observable';
import {retry} from '../../operator/retry';

Observable.prototype.retry = retry;

export var _void: void;