window.esdocSearchIndex = [
  [
    "@reactivex/rxjs/es6/util/objectunsubscribederror.js~objectunsubscribederror",
    "class/es6/util/ObjectUnsubscribedError.js~ObjectUnsubscribedError.html",
    "<span>ObjectUnsubscribedError</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/util/ObjectUnsubscribedError.js</span>",
    "class"
  ],
  [
    "@reactivex/rxjs/es6/observable.js~observable",
    "class/es6/Observable.js~Observable.html",
    "<span>Observable</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/Observable.js</span>",
    "class"
  ],
  [
    "@reactivex/rxjs/es6/operator/buffer.js~buffer",
    "function/index.html#static-function-buffer",
    "<span>buffer</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/buffer.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/buffercount.js~buffercount",
    "function/index.html#static-function-bufferCount",
    "<span>bufferCount</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/bufferCount.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/buffertime.js~buffertime",
    "function/index.html#static-function-bufferTime",
    "<span>bufferTime</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/bufferTime.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/buffertoggle.js~buffertoggle",
    "function/index.html#static-function-bufferToggle",
    "<span>bufferToggle</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/bufferToggle.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/bufferwhen.js~bufferwhen",
    "function/index.html#static-function-bufferWhen",
    "<span>bufferWhen</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/bufferWhen.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/combineall.js~combineall",
    "function/index.html#static-function-combineAll",
    "<span>combineAll</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/combineAll.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/combinelatest-static.js~combinelatest",
    "function/index.html#static-function-combineLatest",
    "<span>combineLatest</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/combineLatest-static.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/combinelatest.js~combinelatest",
    "function/index.html#static-function-combineLatest",
    "<span>combineLatest</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/combineLatest.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/concat-static.js~concat",
    "function/index.html#static-function-concat",
    "<span>concat</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/concat-static.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/concat.js~concat",
    "function/index.html#static-function-concat",
    "<span>concat</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/concat.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/concatall.js~concatall",
    "function/index.html#static-function-concatAll",
    "<span>concatAll</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/concatAll.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/concatmap.js~concatmap",
    "function/index.html#static-function-concatMap",
    "<span>concatMap</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/concatMap.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/concatmapto.js~concatmapto",
    "function/index.html#static-function-concatMapTo",
    "<span>concatMapTo</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/concatMapTo.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/count.js~count",
    "function/index.html#static-function-count",
    "<span>count</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/count.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/filter.js~filter",
    "function/index.html#static-function-filter",
    "<span>filter</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/filter.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/map.js~map",
    "function/index.html#static-function-map",
    "<span>map</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/map.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/operator/mapto.js~mapto",
    "function/index.html#static-function-mapTo",
    "<span>mapTo</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/mapTo.js</span>",
    "function"
  ],
  [
    "@reactivex/rxjs/es6/symbol/rxsubscriber.js~rxsubscriber",
    "variable/index.html#static-variable-rxSubscriber",
    "<span>rxSubscriber</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/symbol/rxSubscriber.js</span>",
    "variable"
  ],
  [
    "@reactivex/rxjs/es6/operator/withlatestfrom.js~withlatestfrom",
    "function/index.html#static-function-withLatestFrom",
    "<span>withLatestFrom</span> <span class=\"search-result-import-path\">@reactivex/rxjs/es6/operator/withLatestFrom.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "es6/coreoperators.js",
    "file/es6/CoreOperators.js.html",
    "es6/CoreOperators.js",
    "file"
  ],
  [
    "es6/innersubscriber.js",
    "file/es6/InnerSubscriber.js.html",
    "es6/InnerSubscriber.js",
    "file"
  ],
  [
    "es6/notification.js",
    "file/es6/Notification.js.html",
    "es6/Notification.js",
    "file"
  ],
  [
    "es6/observable.js",
    "file/es6/Observable.js.html",
    "es6/Observable.js",
    "file"
  ],
  [
    "es6/observable.js~observable#[symbolshim.observable]",
    "class/es6/Observable.js~Observable.html#instance-method-[SymbolShim.observable]",
    "es6/Observable.js~Observable#[SymbolShim.observable]",
    "method"
  ],
  [
    "es6/observable.js~observable#constructor",
    "class/es6/Observable.js~Observable.html#instance-constructor-constructor",
    "es6/Observable.js~Observable#constructor",
    "method"
  ],
  [
    "es6/observable.js~observable#foreach",
    "class/es6/Observable.js~Observable.html#instance-method-forEach",
    "es6/Observable.js~Observable#forEach",
    "method"
  ],
  [
    "es6/observable.js~observable#lift",
    "class/es6/Observable.js~Observable.html#instance-method-lift",
    "es6/Observable.js~Observable#lift",
    "method"
  ],
  [
    "es6/observable.js~observable#subscribe",
    "class/es6/Observable.js~Observable.html#instance-method-subscribe",
    "es6/Observable.js~Observable#subscribe",
    "method"
  ],
  [
    "es6/observer.js",
    "file/es6/Observer.js.html",
    "es6/Observer.js",
    "file"
  ],
  [
    "es6/operator.js",
    "file/es6/Operator.js.html",
    "es6/Operator.js",
    "file"
  ],
  [
    "es6/outersubscriber.js",
    "file/es6/OuterSubscriber.js.html",
    "es6/OuterSubscriber.js",
    "file"
  ],
  [
    "es6/rx.kitchensink.js",
    "file/es6/Rx.KitchenSink.js.html",
    "es6/Rx.KitchenSink.js",
    "file"
  ],
  [
    "es6/rx.js",
    "file/es6/Rx.js.html",
    "es6/Rx.js",
    "file"
  ],
  [
    "es6/scheduler.js",
    "file/es6/Scheduler.js.html",
    "es6/Scheduler.js",
    "file"
  ],
  [
    "es6/subject.js",
    "file/es6/Subject.js.html",
    "es6/Subject.js",
    "file"
  ],
  [
    "es6/subscriber.js",
    "file/es6/Subscriber.js.html",
    "es6/Subscriber.js",
    "file"
  ],
  [
    "es6/subscription.js",
    "file/es6/Subscription.js.html",
    "es6/Subscription.js",
    "file"
  ],
  [
    "es6/add/observable/bindcallback.js",
    "file/es6/add/observable/bindCallback.js.html",
    "es6/add/observable/bindCallback.js",
    "file"
  ],
  [
    "es6/add/observable/defer.js",
    "file/es6/add/observable/defer.js.html",
    "es6/add/observable/defer.js",
    "file"
  ],
  [
    "es6/add/observable/empty.js",
    "file/es6/add/observable/empty.js.html",
    "es6/add/observable/empty.js",
    "file"
  ],
  [
    "es6/add/observable/forkjoin.js",
    "file/es6/add/observable/forkJoin.js.html",
    "es6/add/observable/forkJoin.js",
    "file"
  ],
  [
    "es6/add/observable/from.js",
    "file/es6/add/observable/from.js.html",
    "es6/add/observable/from.js",
    "file"
  ],
  [
    "es6/add/observable/fromarray.js",
    "file/es6/add/observable/fromArray.js.html",
    "es6/add/observable/fromArray.js",
    "file"
  ],
  [
    "es6/add/observable/fromevent.js",
    "file/es6/add/observable/fromEvent.js.html",
    "es6/add/observable/fromEvent.js",
    "file"
  ],
  [
    "es6/add/observable/fromeventpattern.js",
    "file/es6/add/observable/fromEventPattern.js.html",
    "es6/add/observable/fromEventPattern.js",
    "file"
  ],
  [
    "es6/add/observable/frompromise.js",
    "file/es6/add/observable/fromPromise.js.html",
    "es6/add/observable/fromPromise.js",
    "file"
  ],
  [
    "es6/add/observable/interval.js",
    "file/es6/add/observable/interval.js.html",
    "es6/add/observable/interval.js",
    "file"
  ],
  [
    "es6/add/observable/never.js",
    "file/es6/add/observable/never.js.html",
    "es6/add/observable/never.js",
    "file"
  ],
  [
    "es6/add/observable/range.js",
    "file/es6/add/observable/range.js.html",
    "es6/add/observable/range.js",
    "file"
  ],
  [
    "es6/add/observable/throw.js",
    "file/es6/add/observable/throw.js.html",
    "es6/add/observable/throw.js",
    "file"
  ],
  [
    "es6/add/observable/timer.js",
    "file/es6/add/observable/timer.js.html",
    "es6/add/observable/timer.js",
    "file"
  ],
  [
    "es6/add/operator/buffer.js",
    "file/es6/add/operator/buffer.js.html",
    "es6/add/operator/buffer.js",
    "file"
  ],
  [
    "es6/add/operator/buffercount.js",
    "file/es6/add/operator/bufferCount.js.html",
    "es6/add/operator/bufferCount.js",
    "file"
  ],
  [
    "es6/add/operator/buffertime.js",
    "file/es6/add/operator/bufferTime.js.html",
    "es6/add/operator/bufferTime.js",
    "file"
  ],
  [
    "es6/add/operator/buffertoggle.js",
    "file/es6/add/operator/bufferToggle.js.html",
    "es6/add/operator/bufferToggle.js",
    "file"
  ],
  [
    "es6/add/operator/bufferwhen.js",
    "file/es6/add/operator/bufferWhen.js.html",
    "es6/add/operator/bufferWhen.js",
    "file"
  ],
  [
    "es6/add/operator/catch.js",
    "file/es6/add/operator/catch.js.html",
    "es6/add/operator/catch.js",
    "file"
  ],
  [
    "es6/add/operator/combineall.js",
    "file/es6/add/operator/combineAll.js.html",
    "es6/add/operator/combineAll.js",
    "file"
  ],
  [
    "es6/add/operator/combinelatest-static.js",
    "file/es6/add/operator/combineLatest-static.js.html",
    "es6/add/operator/combineLatest-static.js",
    "file"
  ],
  [
    "es6/add/operator/combinelatest.js",
    "file/es6/add/operator/combineLatest.js.html",
    "es6/add/operator/combineLatest.js",
    "file"
  ],
  [
    "es6/add/operator/concat-static.js",
    "file/es6/add/operator/concat-static.js.html",
    "es6/add/operator/concat-static.js",
    "file"
  ],
  [
    "es6/add/operator/concat.js",
    "file/es6/add/operator/concat.js.html",
    "es6/add/operator/concat.js",
    "file"
  ],
  [
    "es6/add/operator/concatall.js",
    "file/es6/add/operator/concatAll.js.html",
    "es6/add/operator/concatAll.js",
    "file"
  ],
  [
    "es6/add/operator/concatmap.js",
    "file/es6/add/operator/concatMap.js.html",
    "es6/add/operator/concatMap.js",
    "file"
  ],
  [
    "es6/add/operator/concatmapto.js",
    "file/es6/add/operator/concatMapTo.js.html",
    "es6/add/operator/concatMapTo.js",
    "file"
  ],
  [
    "es6/add/operator/count.js",
    "file/es6/add/operator/count.js.html",
    "es6/add/operator/count.js",
    "file"
  ],
  [
    "es6/add/operator/debounce.js",
    "file/es6/add/operator/debounce.js.html",
    "es6/add/operator/debounce.js",
    "file"
  ],
  [
    "es6/add/operator/debouncetime.js",
    "file/es6/add/operator/debounceTime.js.html",
    "es6/add/operator/debounceTime.js",
    "file"
  ],
  [
    "es6/add/operator/defaultifempty.js",
    "file/es6/add/operator/defaultIfEmpty.js.html",
    "es6/add/operator/defaultIfEmpty.js",
    "file"
  ],
  [
    "es6/add/operator/delay.js",
    "file/es6/add/operator/delay.js.html",
    "es6/add/operator/delay.js",
    "file"
  ],
  [
    "es6/add/operator/dematerialize.js",
    "file/es6/add/operator/dematerialize.js.html",
    "es6/add/operator/dematerialize.js",
    "file"
  ],
  [
    "es6/add/operator/distinctuntilchanged.js",
    "file/es6/add/operator/distinctUntilChanged.js.html",
    "es6/add/operator/distinctUntilChanged.js",
    "file"
  ],
  [
    "es6/add/operator/do.js",
    "file/es6/add/operator/do.js.html",
    "es6/add/operator/do.js",
    "file"
  ],
  [
    "es6/add/operator/every.js",
    "file/es6/add/operator/every.js.html",
    "es6/add/operator/every.js",
    "file"
  ],
  [
    "es6/add/operator/expand.js",
    "file/es6/add/operator/expand.js.html",
    "es6/add/operator/expand.js",
    "file"
  ],
  [
    "es6/add/operator/extended/distinctuntilkeychanged.js",
    "file/es6/add/operator/extended/distinctUntilKeyChanged.js.html",
    "es6/add/operator/extended/distinctUntilKeyChanged.js",
    "file"
  ],
  [
    "es6/add/operator/extended/elementat.js",
    "file/es6/add/operator/extended/elementAt.js.html",
    "es6/add/operator/extended/elementAt.js",
    "file"
  ],
  [
    "es6/add/operator/extended/find.js",
    "file/es6/add/operator/extended/find.js.html",
    "es6/add/operator/extended/find.js",
    "file"
  ],
  [
    "es6/add/operator/extended/findindex.js",
    "file/es6/add/operator/extended/findIndex.js.html",
    "es6/add/operator/extended/findIndex.js",
    "file"
  ],
  [
    "es6/add/operator/extended/isempty.js",
    "file/es6/add/operator/extended/isEmpty.js.html",
    "es6/add/operator/extended/isEmpty.js",
    "file"
  ],
  [
    "es6/add/operator/extended/max.js",
    "file/es6/add/operator/extended/max.js.html",
    "es6/add/operator/extended/max.js",
    "file"
  ],
  [
    "es6/add/operator/extended/mergescan.js",
    "file/es6/add/operator/extended/mergeScan.js.html",
    "es6/add/operator/extended/mergeScan.js",
    "file"
  ],
  [
    "es6/add/operator/extended/min.js",
    "file/es6/add/operator/extended/min.js.html",
    "es6/add/operator/extended/min.js",
    "file"
  ],
  [
    "es6/add/operator/extended/timeinterval.js",
    "file/es6/add/operator/extended/timeInterval.js.html",
    "es6/add/operator/extended/timeInterval.js",
    "file"
  ],
  [
    "es6/add/operator/filter.js",
    "file/es6/add/operator/filter.js.html",
    "es6/add/operator/filter.js",
    "file"
  ],
  [
    "es6/add/operator/finally.js",
    "file/es6/add/operator/finally.js.html",
    "es6/add/operator/finally.js",
    "file"
  ],
  [
    "es6/add/operator/first.js",
    "file/es6/add/operator/first.js.html",
    "es6/add/operator/first.js",
    "file"
  ],
  [
    "es6/add/operator/groupby.js",
    "file/es6/add/operator/groupBy.js.html",
    "es6/add/operator/groupBy.js",
    "file"
  ],
  [
    "es6/add/operator/ignoreelements.js",
    "file/es6/add/operator/ignoreElements.js.html",
    "es6/add/operator/ignoreElements.js",
    "file"
  ],
  [
    "es6/add/operator/last.js",
    "file/es6/add/operator/last.js.html",
    "es6/add/operator/last.js",
    "file"
  ],
  [
    "es6/add/operator/map.js",
    "file/es6/add/operator/map.js.html",
    "es6/add/operator/map.js",
    "file"
  ],
  [
    "es6/add/operator/mapto.js",
    "file/es6/add/operator/mapTo.js.html",
    "es6/add/operator/mapTo.js",
    "file"
  ],
  [
    "es6/add/operator/materialize.js",
    "file/es6/add/operator/materialize.js.html",
    "es6/add/operator/materialize.js",
    "file"
  ],
  [
    "es6/add/operator/merge-static.js",
    "file/es6/add/operator/merge-static.js.html",
    "es6/add/operator/merge-static.js",
    "file"
  ],
  [
    "es6/add/operator/merge.js",
    "file/es6/add/operator/merge.js.html",
    "es6/add/operator/merge.js",
    "file"
  ],
  [
    "es6/add/operator/mergeall.js",
    "file/es6/add/operator/mergeAll.js.html",
    "es6/add/operator/mergeAll.js",
    "file"
  ],
  [
    "es6/add/operator/mergemap.js",
    "file/es6/add/operator/mergeMap.js.html",
    "es6/add/operator/mergeMap.js",
    "file"
  ],
  [
    "es6/add/operator/mergemapto.js",
    "file/es6/add/operator/mergeMapTo.js.html",
    "es6/add/operator/mergeMapTo.js",
    "file"
  ],
  [
    "es6/add/operator/multicast.js",
    "file/es6/add/operator/multicast.js.html",
    "es6/add/operator/multicast.js",
    "file"
  ],
  [
    "es6/add/operator/observeon.js",
    "file/es6/add/operator/observeOn.js.html",
    "es6/add/operator/observeOn.js",
    "file"
  ],
  [
    "es6/add/operator/partition.js",
    "file/es6/add/operator/partition.js.html",
    "es6/add/operator/partition.js",
    "file"
  ],
  [
    "es6/add/operator/publish.js",
    "file/es6/add/operator/publish.js.html",
    "es6/add/operator/publish.js",
    "file"
  ],
  [
    "es6/add/operator/publishbehavior.js",
    "file/es6/add/operator/publishBehavior.js.html",
    "es6/add/operator/publishBehavior.js",
    "file"
  ],
  [
    "es6/add/operator/publishlast.js",
    "file/es6/add/operator/publishLast.js.html",
    "es6/add/operator/publishLast.js",
    "file"
  ],
  [
    "es6/add/operator/publishreplay.js",
    "file/es6/add/operator/publishReplay.js.html",
    "es6/add/operator/publishReplay.js",
    "file"
  ],
  [
    "es6/add/operator/reduce.js",
    "file/es6/add/operator/reduce.js.html",
    "es6/add/operator/reduce.js",
    "file"
  ],
  [
    "es6/add/operator/repeat.js",
    "file/es6/add/operator/repeat.js.html",
    "es6/add/operator/repeat.js",
    "file"
  ],
  [
    "es6/add/operator/retry.js",
    "file/es6/add/operator/retry.js.html",
    "es6/add/operator/retry.js",
    "file"
  ],
  [
    "es6/add/operator/retrywhen.js",
    "file/es6/add/operator/retryWhen.js.html",
    "es6/add/operator/retryWhen.js",
    "file"
  ],
  [
    "es6/add/operator/sample.js",
    "file/es6/add/operator/sample.js.html",
    "es6/add/operator/sample.js",
    "file"
  ],
  [
    "es6/add/operator/sampletime.js",
    "file/es6/add/operator/sampleTime.js.html",
    "es6/add/operator/sampleTime.js",
    "file"
  ],
  [
    "es6/add/operator/scan.js",
    "file/es6/add/operator/scan.js.html",
    "es6/add/operator/scan.js",
    "file"
  ],
  [
    "es6/add/operator/share.js",
    "file/es6/add/operator/share.js.html",
    "es6/add/operator/share.js",
    "file"
  ],
  [
    "es6/add/operator/single.js",
    "file/es6/add/operator/single.js.html",
    "es6/add/operator/single.js",
    "file"
  ],
  [
    "es6/add/operator/skip.js",
    "file/es6/add/operator/skip.js.html",
    "es6/add/operator/skip.js",
    "file"
  ],
  [
    "es6/add/operator/skipuntil.js",
    "file/es6/add/operator/skipUntil.js.html",
    "es6/add/operator/skipUntil.js",
    "file"
  ],
  [
    "es6/add/operator/skipwhile.js",
    "file/es6/add/operator/skipWhile.js.html",
    "es6/add/operator/skipWhile.js",
    "file"
  ],
  [
    "es6/add/operator/startwith.js",
    "file/es6/add/operator/startWith.js.html",
    "es6/add/operator/startWith.js",
    "file"
  ],
  [
    "es6/add/operator/subscribeon.js",
    "file/es6/add/operator/subscribeOn.js.html",
    "es6/add/operator/subscribeOn.js",
    "file"
  ],
  [
    "es6/add/operator/switch.js",
    "file/es6/add/operator/switch.js.html",
    "es6/add/operator/switch.js",
    "file"
  ],
  [
    "es6/add/operator/switchfirst.js",
    "file/es6/add/operator/switchFirst.js.html",
    "es6/add/operator/switchFirst.js",
    "file"
  ],
  [
    "es6/add/operator/switchfirstmap.js",
    "file/es6/add/operator/switchFirstMap.js.html",
    "es6/add/operator/switchFirstMap.js",
    "file"
  ],
  [
    "es6/add/operator/switchmap.js",
    "file/es6/add/operator/switchMap.js.html",
    "es6/add/operator/switchMap.js",
    "file"
  ],
  [
    "es6/add/operator/switchmapto.js",
    "file/es6/add/operator/switchMapTo.js.html",
    "es6/add/operator/switchMapTo.js",
    "file"
  ],
  [
    "es6/add/operator/take.js",
    "file/es6/add/operator/take.js.html",
    "es6/add/operator/take.js",
    "file"
  ],
  [
    "es6/add/operator/takeuntil.js",
    "file/es6/add/operator/takeUntil.js.html",
    "es6/add/operator/takeUntil.js",
    "file"
  ],
  [
    "es6/add/operator/takewhile.js",
    "file/es6/add/operator/takeWhile.js.html",
    "es6/add/operator/takeWhile.js",
    "file"
  ],
  [
    "es6/add/operator/throttle.js",
    "file/es6/add/operator/throttle.js.html",
    "es6/add/operator/throttle.js",
    "file"
  ],
  [
    "es6/add/operator/throttletime.js",
    "file/es6/add/operator/throttleTime.js.html",
    "es6/add/operator/throttleTime.js",
    "file"
  ],
  [
    "es6/add/operator/timeout.js",
    "file/es6/add/operator/timeout.js.html",
    "es6/add/operator/timeout.js",
    "file"
  ],
  [
    "es6/add/operator/timeoutwith.js",
    "file/es6/add/operator/timeoutWith.js.html",
    "es6/add/operator/timeoutWith.js",
    "file"
  ],
  [
    "es6/add/operator/toarray.js",
    "file/es6/add/operator/toArray.js.html",
    "es6/add/operator/toArray.js",
    "file"
  ],
  [
    "es6/add/operator/topromise.js",
    "file/es6/add/operator/toPromise.js.html",
    "es6/add/operator/toPromise.js",
    "file"
  ],
  [
    "es6/add/operator/window.js",
    "file/es6/add/operator/window.js.html",
    "es6/add/operator/window.js",
    "file"
  ],
  [
    "es6/add/operator/windowcount.js",
    "file/es6/add/operator/windowCount.js.html",
    "es6/add/operator/windowCount.js",
    "file"
  ],
  [
    "es6/add/operator/windowtime.js",
    "file/es6/add/operator/windowTime.js.html",
    "es6/add/operator/windowTime.js",
    "file"
  ],
  [
    "es6/add/operator/windowtoggle.js",
    "file/es6/add/operator/windowToggle.js.html",
    "es6/add/operator/windowToggle.js",
    "file"
  ],
  [
    "es6/add/operator/windowwhen.js",
    "file/es6/add/operator/windowWhen.js.html",
    "es6/add/operator/windowWhen.js",
    "file"
  ],
  [
    "es6/add/operator/withlatestfrom.js",
    "file/es6/add/operator/withLatestFrom.js.html",
    "es6/add/operator/withLatestFrom.js",
    "file"
  ],
  [
    "es6/add/operator/zip-static.js",
    "file/es6/add/operator/zip-static.js.html",
    "es6/add/operator/zip-static.js",
    "file"
  ],
  [
    "es6/add/operator/zip.js",
    "file/es6/add/operator/zip.js.html",
    "es6/add/operator/zip.js",
    "file"
  ],
  [
    "es6/add/operator/zipall.js",
    "file/es6/add/operator/zipAll.js.html",
    "es6/add/operator/zipAll.js",
    "file"
  ],
  [
    "es6/observable/connectableobservable.js",
    "file/es6/observable/ConnectableObservable.js.html",
    "es6/observable/ConnectableObservable.js",
    "file"
  ],
  [
    "es6/observable/iteratorobservable.js",
    "file/es6/observable/IteratorObservable.js.html",
    "es6/observable/IteratorObservable.js",
    "file"
  ],
  [
    "es6/observable/scalarobservable.js",
    "file/es6/observable/ScalarObservable.js.html",
    "es6/observable/ScalarObservable.js",
    "file"
  ],
  [
    "es6/observable/subscribeonobservable.js",
    "file/es6/observable/SubscribeOnObservable.js.html",
    "es6/observable/SubscribeOnObservable.js",
    "file"
  ],
  [
    "es6/observable/bindcallback.js",
    "file/es6/observable/bindCallback.js.html",
    "es6/observable/bindCallback.js",
    "file"
  ],
  [
    "es6/observable/defer.js",
    "file/es6/observable/defer.js.html",
    "es6/observable/defer.js",
    "file"
  ],
  [
    "es6/observable/empty.js",
    "file/es6/observable/empty.js.html",
    "es6/observable/empty.js",
    "file"
  ],
  [
    "es6/observable/forkjoin.js",
    "file/es6/observable/forkJoin.js.html",
    "es6/observable/forkJoin.js",
    "file"
  ],
  [
    "es6/observable/from.js",
    "file/es6/observable/from.js.html",
    "es6/observable/from.js",
    "file"
  ],
  [
    "es6/observable/fromarray.js",
    "file/es6/observable/fromArray.js.html",
    "es6/observable/fromArray.js",
    "file"
  ],
  [
    "es6/observable/fromevent.js",
    "file/es6/observable/fromEvent.js.html",
    "es6/observable/fromEvent.js",
    "file"
  ],
  [
    "es6/observable/fromeventpattern.js",
    "file/es6/observable/fromEventPattern.js.html",
    "es6/observable/fromEventPattern.js",
    "file"
  ],
  [
    "es6/observable/frompromise.js",
    "file/es6/observable/fromPromise.js.html",
    "es6/observable/fromPromise.js",
    "file"
  ],
  [
    "es6/observable/interval.js",
    "file/es6/observable/interval.js.html",
    "es6/observable/interval.js",
    "file"
  ],
  [
    "es6/observable/never.js",
    "file/es6/observable/never.js.html",
    "es6/observable/never.js",
    "file"
  ],
  [
    "es6/observable/range.js",
    "file/es6/observable/range.js.html",
    "es6/observable/range.js",
    "file"
  ],
  [
    "es6/observable/throw.js",
    "file/es6/observable/throw.js.html",
    "es6/observable/throw.js",
    "file"
  ],
  [
    "es6/observable/timer.js",
    "file/es6/observable/timer.js.html",
    "es6/observable/timer.js",
    "file"
  ],
  [
    "es6/operator/buffer.js",
    "file/es6/operator/buffer.js.html",
    "es6/operator/buffer.js",
    "file"
  ],
  [
    "es6/operator/buffercount.js",
    "file/es6/operator/bufferCount.js.html",
    "es6/operator/bufferCount.js",
    "file"
  ],
  [
    "es6/operator/buffertime.js",
    "file/es6/operator/bufferTime.js.html",
    "es6/operator/bufferTime.js",
    "file"
  ],
  [
    "es6/operator/buffertoggle.js",
    "file/es6/operator/bufferToggle.js.html",
    "es6/operator/bufferToggle.js",
    "file"
  ],
  [
    "es6/operator/bufferwhen.js",
    "file/es6/operator/bufferWhen.js.html",
    "es6/operator/bufferWhen.js",
    "file"
  ],
  [
    "es6/operator/catch.js",
    "file/es6/operator/catch.js.html",
    "es6/operator/catch.js",
    "file"
  ],
  [
    "es6/operator/combineall.js",
    "file/es6/operator/combineAll.js.html",
    "es6/operator/combineAll.js",
    "file"
  ],
  [
    "es6/operator/combinelatest-static.js",
    "file/es6/operator/combineLatest-static.js.html",
    "es6/operator/combineLatest-static.js",
    "file"
  ],
  [
    "es6/operator/combinelatest-support.js",
    "file/es6/operator/combineLatest-support.js.html",
    "es6/operator/combineLatest-support.js",
    "file"
  ],
  [
    "es6/operator/combinelatest.js",
    "file/es6/operator/combineLatest.js.html",
    "es6/operator/combineLatest.js",
    "file"
  ],
  [
    "es6/operator/concat-static.js",
    "file/es6/operator/concat-static.js.html",
    "es6/operator/concat-static.js",
    "file"
  ],
  [
    "es6/operator/concat.js",
    "file/es6/operator/concat.js.html",
    "es6/operator/concat.js",
    "file"
  ],
  [
    "es6/operator/concatall.js",
    "file/es6/operator/concatAll.js.html",
    "es6/operator/concatAll.js",
    "file"
  ],
  [
    "es6/operator/concatmap.js",
    "file/es6/operator/concatMap.js.html",
    "es6/operator/concatMap.js",
    "file"
  ],
  [
    "es6/operator/concatmapto.js",
    "file/es6/operator/concatMapTo.js.html",
    "es6/operator/concatMapTo.js",
    "file"
  ],
  [
    "es6/operator/count.js",
    "file/es6/operator/count.js.html",
    "es6/operator/count.js",
    "file"
  ],
  [
    "es6/operator/debounce.js",
    "file/es6/operator/debounce.js.html",
    "es6/operator/debounce.js",
    "file"
  ],
  [
    "es6/operator/debouncetime.js",
    "file/es6/operator/debounceTime.js.html",
    "es6/operator/debounceTime.js",
    "file"
  ],
  [
    "es6/operator/defaultifempty.js",
    "file/es6/operator/defaultIfEmpty.js.html",
    "es6/operator/defaultIfEmpty.js",
    "file"
  ],
  [
    "es6/operator/delay.js",
    "file/es6/operator/delay.js.html",
    "es6/operator/delay.js",
    "file"
  ],
  [
    "es6/operator/dematerialize.js",
    "file/es6/operator/dematerialize.js.html",
    "es6/operator/dematerialize.js",
    "file"
  ],
  [
    "es6/operator/distinctuntilchanged.js",
    "file/es6/operator/distinctUntilChanged.js.html",
    "es6/operator/distinctUntilChanged.js",
    "file"
  ],
  [
    "es6/operator/do.js",
    "file/es6/operator/do.js.html",
    "es6/operator/do.js",
    "file"
  ],
  [
    "es6/operator/every.js",
    "file/es6/operator/every.js.html",
    "es6/operator/every.js",
    "file"
  ],
  [
    "es6/operator/expand-support.js",
    "file/es6/operator/expand-support.js.html",
    "es6/operator/expand-support.js",
    "file"
  ],
  [
    "es6/operator/expand.js",
    "file/es6/operator/expand.js.html",
    "es6/operator/expand.js",
    "file"
  ],
  [
    "es6/operator/extended/distinctuntilkeychanged.js",
    "file/es6/operator/extended/distinctUntilKeyChanged.js.html",
    "es6/operator/extended/distinctUntilKeyChanged.js",
    "file"
  ],
  [
    "es6/operator/extended/elementat.js",
    "file/es6/operator/extended/elementAt.js.html",
    "es6/operator/extended/elementAt.js",
    "file"
  ],
  [
    "es6/operator/extended/find-support.js",
    "file/es6/operator/extended/find-support.js.html",
    "es6/operator/extended/find-support.js",
    "file"
  ],
  [
    "es6/operator/extended/find.js",
    "file/es6/operator/extended/find.js.html",
    "es6/operator/extended/find.js",
    "file"
  ],
  [
    "es6/operator/extended/findindex.js",
    "file/es6/operator/extended/findIndex.js.html",
    "es6/operator/extended/findIndex.js",
    "file"
  ],
  [
    "es6/operator/extended/isempty.js",
    "file/es6/operator/extended/isEmpty.js.html",
    "es6/operator/extended/isEmpty.js",
    "file"
  ],
  [
    "es6/operator/extended/max.js",
    "file/es6/operator/extended/max.js.html",
    "es6/operator/extended/max.js",
    "file"
  ],
  [
    "es6/operator/extended/mergescan.js",
    "file/es6/operator/extended/mergeScan.js.html",
    "es6/operator/extended/mergeScan.js",
    "file"
  ],
  [
    "es6/operator/extended/min.js",
    "file/es6/operator/extended/min.js.html",
    "es6/operator/extended/min.js",
    "file"
  ],
  [
    "es6/operator/extended/timeinterval.js",
    "file/es6/operator/extended/timeInterval.js.html",
    "es6/operator/extended/timeInterval.js",
    "file"
  ],
  [
    "es6/operator/filter.js",
    "file/es6/operator/filter.js.html",
    "es6/operator/filter.js",
    "file"
  ],
  [
    "es6/operator/finally.js",
    "file/es6/operator/finally.js.html",
    "es6/operator/finally.js",
    "file"
  ],
  [
    "es6/operator/first.js",
    "file/es6/operator/first.js.html",
    "es6/operator/first.js",
    "file"
  ],
  [
    "es6/operator/groupby-support.js",
    "file/es6/operator/groupBy-support.js.html",
    "es6/operator/groupBy-support.js",
    "file"
  ],
  [
    "es6/operator/groupby.js",
    "file/es6/operator/groupBy.js.html",
    "es6/operator/groupBy.js",
    "file"
  ],
  [
    "es6/operator/ignoreelements.js",
    "file/es6/operator/ignoreElements.js.html",
    "es6/operator/ignoreElements.js",
    "file"
  ],
  [
    "es6/operator/last.js",
    "file/es6/operator/last.js.html",
    "es6/operator/last.js",
    "file"
  ],
  [
    "es6/operator/map.js",
    "file/es6/operator/map.js.html",
    "es6/operator/map.js",
    "file"
  ],
  [
    "es6/operator/mapto.js",
    "file/es6/operator/mapTo.js.html",
    "es6/operator/mapTo.js",
    "file"
  ],
  [
    "es6/operator/materialize.js",
    "file/es6/operator/materialize.js.html",
    "es6/operator/materialize.js",
    "file"
  ],
  [
    "es6/operator/merge-static.js",
    "file/es6/operator/merge-static.js.html",
    "es6/operator/merge-static.js",
    "file"
  ],
  [
    "es6/operator/merge.js",
    "file/es6/operator/merge.js.html",
    "es6/operator/merge.js",
    "file"
  ],
  [
    "es6/operator/mergeall-support.js",
    "file/es6/operator/mergeAll-support.js.html",
    "es6/operator/mergeAll-support.js",
    "file"
  ],
  [
    "es6/operator/mergeall.js",
    "file/es6/operator/mergeAll.js.html",
    "es6/operator/mergeAll.js",
    "file"
  ],
  [
    "es6/operator/mergemap-support.js",
    "file/es6/operator/mergeMap-support.js.html",
    "es6/operator/mergeMap-support.js",
    "file"
  ],
  [
    "es6/operator/mergemap.js",
    "file/es6/operator/mergeMap.js.html",
    "es6/operator/mergeMap.js",
    "file"
  ],
  [
    "es6/operator/mergemapto-support.js",
    "file/es6/operator/mergeMapTo-support.js.html",
    "es6/operator/mergeMapTo-support.js",
    "file"
  ],
  [
    "es6/operator/mergemapto.js",
    "file/es6/operator/mergeMapTo.js.html",
    "es6/operator/mergeMapTo.js",
    "file"
  ],
  [
    "es6/operator/multicast.js",
    "file/es6/operator/multicast.js.html",
    "es6/operator/multicast.js",
    "file"
  ],
  [
    "es6/operator/observeon-support.js",
    "file/es6/operator/observeOn-support.js.html",
    "es6/operator/observeOn-support.js",
    "file"
  ],
  [
    "es6/operator/observeon.js",
    "file/es6/operator/observeOn.js.html",
    "es6/operator/observeOn.js",
    "file"
  ],
  [
    "es6/operator/partition.js",
    "file/es6/operator/partition.js.html",
    "es6/operator/partition.js",
    "file"
  ],
  [
    "es6/operator/publish.js",
    "file/es6/operator/publish.js.html",
    "es6/operator/publish.js",
    "file"
  ],
  [
    "es6/operator/publishbehavior.js",
    "file/es6/operator/publishBehavior.js.html",
    "es6/operator/publishBehavior.js",
    "file"
  ],
  [
    "es6/operator/publishlast.js",
    "file/es6/operator/publishLast.js.html",
    "es6/operator/publishLast.js",
    "file"
  ],
  [
    "es6/operator/publishreplay.js",
    "file/es6/operator/publishReplay.js.html",
    "es6/operator/publishReplay.js",
    "file"
  ],
  [
    "es6/operator/reduce-support.js",
    "file/es6/operator/reduce-support.js.html",
    "es6/operator/reduce-support.js",
    "file"
  ],
  [
    "es6/operator/reduce.js",
    "file/es6/operator/reduce.js.html",
    "es6/operator/reduce.js",
    "file"
  ],
  [
    "es6/operator/repeat.js",
    "file/es6/operator/repeat.js.html",
    "es6/operator/repeat.js",
    "file"
  ],
  [
    "es6/operator/retry.js",
    "file/es6/operator/retry.js.html",
    "es6/operator/retry.js",
    "file"
  ],
  [
    "es6/operator/retrywhen.js",
    "file/es6/operator/retryWhen.js.html",
    "es6/operator/retryWhen.js",
    "file"
  ],
  [
    "es6/operator/sample.js",
    "file/es6/operator/sample.js.html",
    "es6/operator/sample.js",
    "file"
  ],
  [
    "es6/operator/sampletime.js",
    "file/es6/operator/sampleTime.js.html",
    "es6/operator/sampleTime.js",
    "file"
  ],
  [
    "es6/operator/scan.js",
    "file/es6/operator/scan.js.html",
    "es6/operator/scan.js",
    "file"
  ],
  [
    "es6/operator/share.js",
    "file/es6/operator/share.js.html",
    "es6/operator/share.js",
    "file"
  ],
  [
    "es6/operator/single.js",
    "file/es6/operator/single.js.html",
    "es6/operator/single.js",
    "file"
  ],
  [
    "es6/operator/skip.js",
    "file/es6/operator/skip.js.html",
    "es6/operator/skip.js",
    "file"
  ],
  [
    "es6/operator/skipuntil.js",
    "file/es6/operator/skipUntil.js.html",
    "es6/operator/skipUntil.js",
    "file"
  ],
  [
    "es6/operator/skipwhile.js",
    "file/es6/operator/skipWhile.js.html",
    "es6/operator/skipWhile.js",
    "file"
  ],
  [
    "es6/operator/startwith.js",
    "file/es6/operator/startWith.js.html",
    "es6/operator/startWith.js",
    "file"
  ],
  [
    "es6/operator/subscribeon.js",
    "file/es6/operator/subscribeOn.js.html",
    "es6/operator/subscribeOn.js",
    "file"
  ],
  [
    "es6/operator/switch.js",
    "file/es6/operator/switch.js.html",
    "es6/operator/switch.js",
    "file"
  ],
  [
    "es6/operator/switchfirst.js",
    "file/es6/operator/switchFirst.js.html",
    "es6/operator/switchFirst.js",
    "file"
  ],
  [
    "es6/operator/switchfirstmap.js",
    "file/es6/operator/switchFirstMap.js.html",
    "es6/operator/switchFirstMap.js",
    "file"
  ],
  [
    "es6/operator/switchmap.js",
    "file/es6/operator/switchMap.js.html",
    "es6/operator/switchMap.js",
    "file"
  ],
  [
    "es6/operator/switchmapto.js",
    "file/es6/operator/switchMapTo.js.html",
    "es6/operator/switchMapTo.js",
    "file"
  ],
  [
    "es6/operator/take.js",
    "file/es6/operator/take.js.html",
    "es6/operator/take.js",
    "file"
  ],
  [
    "es6/operator/takeuntil.js",
    "file/es6/operator/takeUntil.js.html",
    "es6/operator/takeUntil.js",
    "file"
  ],
  [
    "es6/operator/takewhile.js",
    "file/es6/operator/takeWhile.js.html",
    "es6/operator/takeWhile.js",
    "file"
  ],
  [
    "es6/operator/throttle.js",
    "file/es6/operator/throttle.js.html",
    "es6/operator/throttle.js",
    "file"
  ],
  [
    "es6/operator/throttletime.js",
    "file/es6/operator/throttleTime.js.html",
    "es6/operator/throttleTime.js",
    "file"
  ],
  [
    "es6/operator/timeout.js",
    "file/es6/operator/timeout.js.html",
    "es6/operator/timeout.js",
    "file"
  ],
  [
    "es6/operator/timeoutwith.js",
    "file/es6/operator/timeoutWith.js.html",
    "es6/operator/timeoutWith.js",
    "file"
  ],
  [
    "es6/operator/toarray.js",
    "file/es6/operator/toArray.js.html",
    "es6/operator/toArray.js",
    "file"
  ],
  [
    "es6/operator/topromise.js",
    "file/es6/operator/toPromise.js.html",
    "es6/operator/toPromise.js",
    "file"
  ],
  [
    "es6/operator/window.js",
    "file/es6/operator/window.js.html",
    "es6/operator/window.js",
    "file"
  ],
  [
    "es6/operator/windowcount.js",
    "file/es6/operator/windowCount.js.html",
    "es6/operator/windowCount.js",
    "file"
  ],
  [
    "es6/operator/windowtime.js",
    "file/es6/operator/windowTime.js.html",
    "es6/operator/windowTime.js",
    "file"
  ],
  [
    "es6/operator/windowtoggle.js",
    "file/es6/operator/windowToggle.js.html",
    "es6/operator/windowToggle.js",
    "file"
  ],
  [
    "es6/operator/windowwhen.js",
    "file/es6/operator/windowWhen.js.html",
    "es6/operator/windowWhen.js",
    "file"
  ],
  [
    "es6/operator/withlatestfrom.js",
    "file/es6/operator/withLatestFrom.js.html",
    "es6/operator/withLatestFrom.js",
    "file"
  ],
  [
    "es6/operator/zip-static.js",
    "file/es6/operator/zip-static.js.html",
    "es6/operator/zip-static.js",
    "file"
  ],
  [
    "es6/operator/zip-support.js",
    "file/es6/operator/zip-support.js.html",
    "es6/operator/zip-support.js",
    "file"
  ],
  [
    "es6/operator/zip.js",
    "file/es6/operator/zip.js.html",
    "es6/operator/zip.js",
    "file"
  ],
  [
    "es6/operator/zipall.js",
    "file/es6/operator/zipAll.js.html",
    "es6/operator/zipAll.js",
    "file"
  ],
  [
    "es6/scheduler/action.js",
    "file/es6/scheduler/Action.js.html",
    "es6/scheduler/Action.js",
    "file"
  ],
  [
    "es6/scheduler/asapaction.js",
    "file/es6/scheduler/AsapAction.js.html",
    "es6/scheduler/AsapAction.js",
    "file"
  ],
  [
    "es6/scheduler/asapscheduler.js",
    "file/es6/scheduler/AsapScheduler.js.html",
    "es6/scheduler/AsapScheduler.js",
    "file"
  ],
  [
    "es6/scheduler/futureaction.js",
    "file/es6/scheduler/FutureAction.js.html",
    "es6/scheduler/FutureAction.js",
    "file"
  ],
  [
    "es6/scheduler/queueaction.js",
    "file/es6/scheduler/QueueAction.js.html",
    "es6/scheduler/QueueAction.js",
    "file"
  ],
  [
    "es6/scheduler/queuescheduler.js",
    "file/es6/scheduler/QueueScheduler.js.html",
    "es6/scheduler/QueueScheduler.js",
    "file"
  ],
  [
    "es6/scheduler/virtualtimescheduler.js",
    "file/es6/scheduler/VirtualTimeScheduler.js.html",
    "es6/scheduler/VirtualTimeScheduler.js",
    "file"
  ],
  [
    "es6/scheduler/asap.js",
    "file/es6/scheduler/asap.js.html",
    "es6/scheduler/asap.js",
    "file"
  ],
  [
    "es6/scheduler/queue.js",
    "file/es6/scheduler/queue.js.html",
    "es6/scheduler/queue.js",
    "file"
  ],
  [
    "es6/subject/asyncsubject.js",
    "file/es6/subject/AsyncSubject.js.html",
    "es6/subject/AsyncSubject.js",
    "file"
  ],
  [
    "es6/subject/behaviorsubject.js",
    "file/es6/subject/BehaviorSubject.js.html",
    "es6/subject/BehaviorSubject.js",
    "file"
  ],
  [
    "es6/subject/replaysubject.js",
    "file/es6/subject/ReplaySubject.js.html",
    "es6/subject/ReplaySubject.js",
    "file"
  ],
  [
    "es6/subject/subjectsubscription.js",
    "file/es6/subject/SubjectSubscription.js.html",
    "es6/subject/SubjectSubscription.js",
    "file"
  ],
  [
    "es6/symbol/rxsubscriber.js",
    "file/es6/symbol/rxSubscriber.js.html",
    "es6/symbol/rxSubscriber.js",
    "file"
  ],
  [
    "es6/testing/coldobservable.js",
    "file/es6/testing/ColdObservable.js.html",
    "es6/testing/ColdObservable.js",
    "file"
  ],
  [
    "es6/testing/hotobservable.js",
    "file/es6/testing/HotObservable.js.html",
    "es6/testing/HotObservable.js",
    "file"
  ],
  [
    "es6/testing/subscriptionlog.js",
    "file/es6/testing/SubscriptionLog.js.html",
    "es6/testing/SubscriptionLog.js",
    "file"
  ],
  [
    "es6/testing/subscriptionloggable.js",
    "file/es6/testing/SubscriptionLoggable.js.html",
    "es6/testing/SubscriptionLoggable.js",
    "file"
  ],
  [
    "es6/testing/testmessage.js",
    "file/es6/testing/TestMessage.js.html",
    "es6/testing/TestMessage.js",
    "file"
  ],
  [
    "es6/testing/testscheduler.js",
    "file/es6/testing/TestScheduler.js.html",
    "es6/testing/TestScheduler.js",
    "file"
  ],
  [
    "es6/util/argumentoutofrangeerror.js",
    "file/es6/util/ArgumentOutOfRangeError.js.html",
    "es6/util/ArgumentOutOfRangeError.js",
    "file"
  ],
  [
    "es6/util/emptyerror.js",
    "file/es6/util/EmptyError.js.html",
    "es6/util/EmptyError.js",
    "file"
  ],
  [
    "es6/util/fastmap.js",
    "file/es6/util/FastMap.js.html",
    "es6/util/FastMap.js",
    "file"
  ],
  [
    "es6/util/immediate.js",
    "file/es6/util/Immediate.js.html",
    "es6/util/Immediate.js",
    "file"
  ],
  [
    "es6/util/map.js",
    "file/es6/util/Map.js.html",
    "es6/util/Map.js",
    "file"
  ],
  [
    "es6/util/mappolyfill.js",
    "file/es6/util/MapPolyfill.js.html",
    "es6/util/MapPolyfill.js",
    "file"
  ],
  [
    "es6/util/objectunsubscribederror.js",
    "file/es6/util/ObjectUnsubscribedError.js.html",
    "es6/util/ObjectUnsubscribedError.js",
    "file"
  ],
  [
    "es6/util/symbolshim.js",
    "file/es6/util/SymbolShim.js.html",
    "es6/util/SymbolShim.js",
    "file"
  ],
  [
    "es6/util/applymixins.js",
    "file/es6/util/applyMixins.js.html",
    "es6/util/applyMixins.js",
    "file"
  ],
  [
    "es6/util/bindcallback.js",
    "file/es6/util/bindCallback.js.html",
    "es6/util/bindCallback.js",
    "file"
  ],
  [
    "es6/util/errorobject.js",
    "file/es6/util/errorObject.js.html",
    "es6/util/errorObject.js",
    "file"
  ],
  [
    "es6/util/isarray.js",
    "file/es6/util/isArray.js.html",
    "es6/util/isArray.js",
    "file"
  ],
  [
    "es6/util/isdate.js",
    "file/es6/util/isDate.js.html",
    "es6/util/isDate.js",
    "file"
  ],
  [
    "es6/util/isnumeric.js",
    "file/es6/util/isNumeric.js.html",
    "es6/util/isNumeric.js",
    "file"
  ],
  [
    "es6/util/ispromise.js",
    "file/es6/util/isPromise.js.html",
    "es6/util/isPromise.js",
    "file"
  ],
  [
    "es6/util/isscheduler.js",
    "file/es6/util/isScheduler.js.html",
    "es6/util/isScheduler.js",
    "file"
  ],
  [
    "es6/util/noop.js",
    "file/es6/util/noop.js.html",
    "es6/util/noop.js",
    "file"
  ],
  [
    "es6/util/not.js",
    "file/es6/util/not.js.html",
    "es6/util/not.js",
    "file"
  ],
  [
    "es6/util/root.js",
    "file/es6/util/root.js.html",
    "es6/util/root.js",
    "file"
  ],
  [
    "es6/util/subscribetoresult.js",
    "file/es6/util/subscribeToResult.js.html",
    "es6/util/subscribeToResult.js",
    "file"
  ],
  [
    "es6/util/throwerror.js",
    "file/es6/util/throwError.js.html",
    "es6/util/throwError.js",
    "file"
  ],
  [
    "es6/util/trycatch.js",
    "file/es6/util/tryCatch.js.html",
    "es6/util/tryCatch.js",
    "file"
  ],
  [
    "es6/util/tryoronerror.js",
    "file/es6/util/tryOrOnError.js.html",
    "es6/util/tryOrOnError.js",
    "file"
  ]
]