name: CI

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18', '20']

    name: Node ${{ matrix.node }} build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: install
        run: |
          npm install -g yarn@latest
          yarn install
      - name: rxjs lint
        run: yarn workspaces rxjs lint
      - name: rxjs build
        run: yarn workspaces rxjs build
      - name: rxjs test
        run: yarn workspaces rxjs test
      - name: rxjs dtslint
        run: yarn workspaces rxjs dtslint
      - name: rxjs test:import
        if: ${{ matrix.node == '18' || matrix.node == '20' }}
        run: yarn workspaces rxjs test:import
      - name: rxjs test:esm
        if: ${{ matrix.node == '16' || matrix.node == '18' || matrix.node == '20' }}
        run: yarn workspaces rxjs test:esm
      - name: rxjs.dev build
        run: yarn workspaces rxjs.dev build --prod
      - name: rxjs.dev test
        run: yarn workspaces rxjs.dev test --watch=false --browsers=ChromeHeadless
