name: CI

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18']

    name: Node ${{ matrix.node }} build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: install
        run: |
          npm install -g npm@latest
          npm ci
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build:package
      - name: test
        run: |
          npm test
          npm run test:side-effects
      - name: dtslint
        run: npm run dtslint
      - name: import
        if: ${{ matrix.node == '18' }}
        run: npm run test:import
      - name: import
        if: ${{ matrix.node == '16' || matrix.node == '18' }}
        run: npm run test:esm
      - name: docs
        run: |
          cd docs_app
          npm run setup
          npm run build
