name: CI (ts@latest)

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  push:
    branches: ['master']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['24']

    name: ts@latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node }}

      - name: build
        run: |
          pnpm --filter @rxjs/observable-polyfill run build
          pnpm --filter rxjs add --save-dev --lockfile=false typescript@latest
          pnpm --filter rxjs run build
