name: CI (ts@latest)

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  push:
    branches: ['master']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['24']

    name: ts@latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node }}

      - name: build
        run: |
          pnpm --filter rxjs add --save-dev --lockfile=false typescript@latest @types/node@latest
          pnpm nx compile rxjs
