name: CI (ts@latest)

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20']

    name: ts@latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: build
        run: |
          npm install -g yarn@latest
          yarn install
          yarn add typescript@latest @types/node@latest --peer --no-save
          yarn workspace rxjs compile
